// module.exports.productRoutes = require("./product.routes");
// module.exports.userRoutes = require("./user.routes");
module.exports.accountantRoutes = require("./accountant.routes");
module.exports.employeeRoutes = require("./employee.routes");
module.exports.customerRoutes = require("./customer.routes");
module.exports.invoiceRoutes = require("./invoice.routes");
module.exports.generatedInvoiceRoutes = require("./generatedInvoice.routes");
module.exports.serviceDesc = require("./serviceDescription.routes");
module.exports.varRate = require("./varRate.routes");
